/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package validroman;

public class App {


    public static void main(String[] args) {
        RomanNumeral rom = new RomanNumeral("MCMXCIX");
        rom.printIfValid();
        rom = new RomanNumeral("MMMXCXLII");
        rom.printIfValid();
    }
}
